travel/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('authentication.urls')),
    path('',include('voyage.urls',namespace="voyage_app")),
  
]

voyage/urls.py
from django.urls import path

from .views import (
    HomeView,
    TravelInspirationView,
    TravelInspirationCreateView,
    TravelInspirationListView,
    FavoriteDetailView,
    FavoritesListView,
    TravelInspirationDetailView,
    CreateFavoriteView,
    TravelInspirationReSearchView,
    create_travel_inspiration,
)

app_name = "voyage_app"

urlpatterns = [
    # DEFAULT HOME
    path("",HomeView.as_view(),name="home"),

    # TRAVEL INSPIRATION ROUTE

    path("api/travel-inspiration-home/",TravelInspirationView.as_view(),name="travel-inspiration-home"),
    path("api/travel-inspiration-create/",create_travel_inspiration,name="travel-inspiration-create"),
    path("api/travel-inspiration/",TravelInspirationListView.as_view(),name="travel-inspiration-list"),
    path("api/travel-inspiration/<int:id>/",TravelInspirationDetailView.as_view(),name="travel-inspiration-detail"),
    path("api/travel-inspiration/search/",TravelInspirationReSearchView.as_view(),name='search-travel'),

    # FAVORITE ROUTE 
    path("api/travel-inspiration/favorites/",FavoritesListView.as_view(),name="favorite-list"),
    path("api/travel-inspiration/favorites/<int:id>/",FavoriteDetailView.as_view(),name="favorite-detail"),
    path("api/favorites/create/<int:id>/",CreateFavoriteView.as_view(),name="favorite-create"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Travel Inspiration  | 
              {% block title %}

            {% endblock %}</title>
        <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/14273d579a.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <!-- Font awesome bootstrap css-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!--link rel="stylesheet" href="css/style.css"-->
    
    <!--JQuery-->
    <script src="https://code.jquery.com/jquery-3.1.1.js"></script>
    
    
    <link href="{% static 'base.css' %}" rel="stylesheet">

    <script src="js/site.js"></script>    
    

    </head>
    <body>
        <header  class="my-5 ">
        <nav class="navbar  navbar-expand-md  navbar-light fixed-top  "style="background-color:#00008B">
            <!--a href="..&/index.html" class="btn bg-primary text-white position-fixed ms-2" data-bs-toggle="tooltip"
            data-bs-placement="right" title="Ne pas inclure dans l'intégration">Retour</a-->
            <div class="container-fluid py-3  ">
                    <a href="index.html" class="navbar-brand text-uppercase fw-bold text-warning"> 
                      <span class="bg-gradiant text-light p-2 rounded-3">TRAVEL</span>  
                        SITE</a>

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="navbar-collapse collapse justify-content-end" id="navbarNav">

                        <ul class="navbar-nav">
                            <li class="nav-item active">
                                <a class="nav-link text-light" href="{% url 'voyage_app:home' %}">Home</a>
                            </li>
                <li class="nav-item active">
                    <a class="nav-link text-light" href="{% url 'voyage_app:travel-inspiration-home' %}">Travel Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'voyage_app:travel-inspiration-list' %}">Travel Catalogue</a>
                </li>
                           
                            <li class="nav-item">
                                <a class="nav-link text-light" href="{% url 'voyage_app:travel-inspiration-create' %}">Add Travel Inspiration</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-light" href="{% url 'voyage_app:favorite-list' %}">Mes Favoris</a>
                            </li>
                          


                            <!--li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light fw-bolder" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                  {{request.user.username }}
                                </a>
                                <ul class="dropdown-menu bg-warning" aria-labelledby="navbarDropdown">
                                  <li><a class="dropdown-item text-light" href="#">Profile</a></li>
                                  <li><a class="dropdown-item text-light" href="#">Deconnextion</a></li>
                                  <li><hr class="dropdown-divider"></li>
                                  <li><a class="dropdown-item" href="#">Connexion</a></li>
                                </ul>
                              </li-->
                        </ul>
                        
            </div>
            </div>

        </nav>

    </div>
    </header>

    <div class="container position-relative " style="margin-top : 50px;">

        <div class="row">
         
         <div class="col col-md-8 mx-auto" style="margin-top : 50px;">
                <form action="#" method="GET">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Research by title..." aria-label="Recipient's username" aria-describedby="button-addon2" name="product_keyword" required>
                        <button class="btn btn-outline-primary" type="submit" id="button-addon2">Rechercher</button>
                      </div>
                </form>
         </div>
        </div>
    </div
    
    <main class="mt-2">
        {% block content %}
    
        {% endblock %}
    </main>
    
 <footer>
 </footer>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    </body>
    </html>

templates/create_travel_inspiration.html
{% extends 'base.html' %}

{% block title %}
 Add Travel Inspiration
{% endblock %}

  {% block content %}

  <h1 class=" p-5 text-center border-b-2">Rechercher un Travel Inspiration en fonction entrées</h1>
  <div class="container">
    
   <div class="row">
    
    <div class="col-sm-12 col-md-8 mx-auto" >
        <form action="" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            {{form.as_p}}
         <button type="submit" class ="btn btn-primary"> Valider </button>
        </form>
    </div>

  </div>

  </div>

   {% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}
  Home
{% endblock %}

  {% block content %}

  <h1 class=" p-5">Bienvenue notre plateforme  de Voyage Inspiration !! Nous somme là pour votre satisfaction</h1>
  <div class="container">

   <div class="row gy-2">
    {% for travel in travels %}
    <div class="col col-md-3">
      
      <div class="card shadow border-1 border-primary img-fluid mb-2" style="width: 18rem; height:400px; object-fit:cover;">
        <div class="card-body">
          <h5 class="card-title fw-bolder"> Budget : <strong>{{travel.budget}}</strong></h5>
          <p class="card-text text-center mt-3"> Date Aller : {{travel.travel_date_start}}</p>
          <p class="card-text text-center mt-3"> Date de Retour : {{travel.travel_date_end}} </p>

          <a href="#" class="btn btn-primary fs-6">Add to Favoris</a>
          <a href="#" class="btn btn-dark fs-6">Details</a>

        </div>
      </div>

    </div>

    {% endfor %}
  </div>
  
  </div>


 <!-- BOOTSTRAP AND DJANGO PAGINATION-->
 <div class="row">
  <div class="col">
<nav aria-label="...">
  <ul class="pagination">
    {% if travels.has_previous %}
    <li class="page-item">
      <a class="page-link"  href="?page={{ travels.previous_page_number }}"><i class="fa fa-angle-double-left"></i></a>
    </li>
    {% else %}
      <li class="page-item disabled">
      <a class="page-link"  href="#" tabindex="1" aria-disabled="true"><i class="fa fa-angle-double-left"></i></a>
    </li>
    {% endif %}

  </ul>
</nav>
</div>
</div>
   {% endblock %}